import type { PulseItem, SourceConnection } from "../types";

/**
 * Demo content, loaded only when the user explicitly asks for it from Settings.
 * Pulse never seeds these automatically - an empty library stays empty until a
 * real sync succeeds.
 */
export const INITIAL_SAMPLE_ITEMS: PulseItem[] = [
  {
    id: "demo-repo-vllm",
    source: "github",
    sourceType: "github_trending",
    category: "repo",
    field: "ai_ml",
    title: "vllm-project/vllm: High-throughput and memory-efficient LLM serving engine",
    url: "https://github.com/vllm-project/vllm",
    body: "vLLM is a fast and easy-to-use library for LLM inference and serving with PagedAttention, continuous batching, and CUDA kernel optimizations.",
    author: "vllm-project",
    authorUrl: "https://github.com/vllm-project",
    score: 41800,
    commentsCount: 2340,
    publishedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    state: "inbox",
    tags: ["inference-serving", "inference", "llm"],
    topic: "inference-serving",
    signal: 0.9,
    primarySource: true,
    whyKey: "new-tool-release",
    why: "New tool or library release",
    extractedResources: [
      { type: "repo", name: "vllm-project/vllm", url: "https://github.com/vllm-project/vllm" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-repo-deepseek",
    source: "github",
    sourceType: "github_trending",
    category: "repo",
    field: "ai_ml",
    title: "deepseek-ai/DeepSeek-V3: Multi-head Latent Attention & DeepSeekMoE Architecture",
    url: "https://github.com/deepseek-ai/DeepSeek-V3",
    body: "Official repository for DeepSeek-V3, a 671B parameter Mixture-of-Experts model with FP8 mixed precision training and multi-head latent attention.",
    author: "deepseek-ai",
    authorUrl: "https://github.com/deepseek-ai",
    score: 52400,
    commentsCount: 3890,
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    state: "important",
    tags: ["model-releases", "llm"],
    topic: "model-releases",
    signal: 1,
    primarySource: true,
    whyKey: "major-model-release",
    why: "Major model release",
    extractedResources: [
      { type: "repo", name: "deepseek-ai/DeepSeek-V3", url: "https://github.com/deepseek-ai/DeepSeek-V3" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-repo-tauri",
    source: "github",
    sourceType: "github_trending",
    category: "repo",
    field: "systems_infra",
    title: "tauri-apps/tauri: Build smaller, faster, and more secure desktop applications",
    url: "https://github.com/tauri-apps/tauri",
    body: "Tauri v2 brings native multiplatform support, enhanced webview IPC, mobile targets, and an extensible Rust plugin ecosystem.",
    author: "tauri-apps",
    authorUrl: "https://github.com/tauri-apps",
    score: 84000,
    commentsCount: 4500,
    publishedAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    state: "saved",
    tags: ["systems-runtime", "rust"],
    topic: "systems-runtime",
    signal: 0.7,
    primarySource: true,
    whyKey: "systems-technique",
    why: "Systems or infrastructure technique",
    extractedResources: [
      { type: "repo", name: "tauri-apps/tauri", url: "https://github.com/tauri-apps/tauri" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-paper-mcts",
    source: "arxiv",
    sourceType: "arxiv_paper",
    category: "paper",
    field: "ai_ml",
    title: "Scaling Test-Time Compute in Reasoning Models via Monte Carlo Tree Search",
    url: "https://arxiv.org/abs/2408.03314",
    body: "We demonstrate that allocating extended compute at test time via verified reward model search matches the performance of a 10x larger pre-trained model.",
    author: "arXiv cs.AI",
    authorUrl: "https://arxiv.org",
    score: 430,
    commentsCount: 88,
    publishedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    state: "inbox",
    tags: ["training-methods", "benchmarks-eval"],
    topic: "training-methods",
    signal: 0.8,
    primarySource: true,
    whyKey: "benchmark-or-paper",
    why: "Benchmark or research result",
    extractedResources: [
      { type: "paper", name: "arXiv:2408.03314", url: "https://arxiv.org/abs/2408.03314" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-paper-grpo",
    source: "huggingface",
    sourceType: "huggingface_paper",
    category: "paper",
    field: "ai_ml",
    title: "GRPO: Group Relative Policy Optimization for Efficient RL in Large Language Models",
    url: "https://huggingface.co/papers/2402.03300",
    body: "GRPO eliminates the need for an explicit critic network during reinforcement learning, substantially reducing GPU memory during post-training alignment.",
    author: "Hugging Face Daily Papers",
    authorUrl: "https://huggingface.co/papers",
    score: 620,
    commentsCount: 145,
    publishedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    state: "inbox",
    tags: ["training-methods", "llm"],
    topic: "training-methods",
    signal: 0.75,
    primarySource: true,
    whyKey: "benchmark-or-paper",
    why: "Benchmark or research result",
    extractedResources: [
      { type: "paper", name: "HuggingFace:2402.03300", url: "https://huggingface.co/papers/2402.03300" },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-resource-shadcn",
    source: "producthunt",
    sourceType: "producthunt_post",
    category: "resource",
    field: "web_frontend",
    title: "shadcn/ui: Beautifully designed components you can copy and paste into your apps",
    url: "https://ui.shadcn.com",
    body: "Accessible and customizable components built with Tailwind CSS. Not a component library, but an open collection of building blocks you own.",
    author: "shadcn",
    authorUrl: "https://twitter.com/shadcn",
    score: 820,
    commentsCount: 112,
    publishedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    state: "saved",
    tags: ["web-frontend", "react"],
    topic: "web-frontend",
    signal: 0.5,
    primarySource: false,
    whyKey: "new-tool-release",
    why: "New tool or library release",
    extractedResources: [{ type: "product", name: "shadcn/ui", url: "https://ui.shadcn.com" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-resource-agents",
    source: "devto",
    sourceType: "devto_article",
    category: "resource",
    field: "developer_tools",
    title: "Awesome AI Agents: Curated list of autonomous frameworks, harnesses, and benchmarks",
    url: "https://github.com/e2b-dev/awesome-ai-agents",
    body: "A comprehensive index of sandbox runtimes, tool-calling frameworks, and evaluation suites for agent architectures.",
    author: "e2b",
    authorUrl: "https://github.com/e2b-dev",
    score: 410,
    commentsCount: 45,
    publishedAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    state: "inbox",
    tags: ["llm-agents", "open-source"],
    topic: "llm-agents",
    signal: 0.4,
    primarySource: false,
    whyKey: "other",
    why: "Notable development",
    extractedResources: [
      {
        type: "repo",
        name: "e2b-dev/awesome-ai-agents",
        url: "https://github.com/e2b-dev/awesome-ai-agents",
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-news-helmsman",
    source: "hackernews",
    sourceType: "hackernews_story",
    category: "news",
    field: "developer_tools",
    title: "Show HN: Helmsman – Agent-first browser runtime with unified stealth and MCP",
    url: "https://news.ycombinator.com/item?id=40001234",
    body: "Helmsman is an open-source browser automation runtime that evades anti-bot detection by default and serves tools natively over MCP.",
    author: "kaushal",
    authorUrl: "https://news.ycombinator.com/user?id=kaushal",
    score: 495,
    commentsCount: 168,
    publishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    state: "important",
    tags: ["browser-automation", "dev-tooling"],
    topic: "browser-automation",
    signal: 0.65,
    primarySource: true,
    whyKey: "new-tool-release",
    why: "New tool or library release",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-news-browserlocks",
    source: "lobsters",
    sourceType: "lobsters_story",
    category: "news",
    field: "systems_infra",
    title: "Why Chromium's single-process profile lock fails in automated orchestrations",
    url: "https://lobste.rs/s/browser-locks-2026",
    body: "An architectural exploration of SingletonLock symlinks, stale UNIX domain sockets, and shared filesystem state under fast process turnover.",
    author: "sysdev",
    authorUrl: "https://lobste.rs/~sysdev",
    score: 86,
    commentsCount: 32,
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    state: "inbox",
    tags: ["systems-runtime", "browser-automation"],
    topic: "systems-runtime",
    signal: 0.55,
    primarySource: true,
    whyKey: "systems-technique",
    why: "Systems or infrastructure technique",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-news-localllama",
    source: "reddit",
    sourceType: "reddit_post",
    category: "news",
    field: "ai_ml",
    title: "r/LocalLLaMA: Running DeepSeek-R1 70B locally at 32 tok/s on Mac Studio M2 Ultra",
    url: "https://reddit.com/r/LocalLLaMA/comments/deepseek_m2_benchmark",
    body: "Complete setup guide using llama.cpp with the Metal backend, Q4_K_M quantization, and a 64k context window with zero memory swap.",
    author: "local_tuner",
    authorUrl: "https://reddit.com/user/local_tuner",
    score: 1140,
    commentsCount: 230,
    publishedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    state: "inbox",
    tags: ["inference-serving", "hardware-chips"],
    topic: "inference-serving",
    signal: 0.6,
    primarySource: false,
    whyKey: "benchmark-or-paper",
    why: "Benchmark or research result",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-news-karpathy",
    source: "twitter",
    sourceType: "twitter_tweet",
    category: "news",
    field: "ai_ml",
    title: "@karpathy on Test-Time Compute and reasoning architectures",
    url: "https://x.com/karpathy/status/1880000000000000000",
    body: "The paradigm is shifting from pre-training token scales to test-time search budgets. If an agent can verify each step, compute scaling happens at runtime.",
    author: "Andrej Karpathy",
    authorUrl: "https://x.com/karpathy",
    score: 8420,
    commentsCount: 650,
    publishedAt: new Date(Date.now() - 3600000 * 7).toISOString(),
    state: "important",
    tags: ["community-debate", "training-methods"],
    topic: "community-debate",
    signal: 0.5,
    primarySource: false,
    whyKey: "community-debate",
    why: "Ongoing community debate",
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_ITEM_IDS = INITIAL_SAMPLE_ITEMS.map((item) => item.id);

/**
 * Ids written by an earlier build that seeded demo content into the real library
 * on every sync. Purged once on schema upgrade so fake rows stop masquerading as
 * collected data.
 */
export const LEGACY_DEMO_ITEM_IDS = [
  "repo-1",
  "repo-2",
  "repo-3",
  "paper-1",
  "paper-2",
  "resource-1",
  "resource-2",
  "news-1",
  "news-2",
  "reddit-1",
  "twitter-1",
];

/**
 * Default source catalog. Rows are persisted to the `sources` table on first run
 * so connection state and last-sync times survive restarts.
 */
export const DEFAULT_SOURCES: SourceConnection[] = [
  {
    id: "reddit",
    source: "reddit",
    name: "Reddit",
    authType: "browser_profile",
    profileName: "reddit",
    siteDomain: "reddit.com",
    isConnected: false,
    monitoredChannels: ["r/localllama", "r/programming", "r/MachineLearning"],
    options: {
      subreddits: [
        "localllama",
        "programming",
        "MachineLearning",
        "artificial",
        "technology",
        "webdev",
        "devops",
        "selfhosted",
        "rust",
        "opensource",
        "startups",
      ],
      sort: "hot",
      limit: 20,
    },
    enabled: true,
  },
  {
    id: "twitter",
    source: "twitter",
    name: "Twitter / X",
    authType: "browser_profile",
    profileName: "twitter",
    siteDomain: "x.com",
    isConnected: false,
    monitoredChannels: ["keyword search"],
    options: {
      mode: "search",
      queries: ["AI agents", "LLM", "open source", "developer tools", "local inference"],
      limit: 15,
    },
    enabled: true,
  },
  {
    id: "linkedin",
    source: "linkedin",
    name: "LinkedIn Jobs",
    authType: "browser_profile",
    profileName: "linkedin",
    siteDomain: "linkedin.com",
    isConnected: false,
    monitoredChannels: ["Software Engineer"],
    options: { keywords: "Software Engineer", limit: 15 },
    enabled: false,
  },
  {
    id: "hackernews",
    source: "hackernews",
    name: "Hacker News",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["Front page"],
    options: { mode: "feed", limit: 30 },
    enabled: true,
  },
  {
    id: "hackernews-search",
    source: "hackernews",
    name: "Hacker News Search",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["keyword search"],
    options: {
      mode: "search",
      queries: [
        "AI agents",
        "LLM",
        "local inference",
        "quantization",
        "open source",
        "developer tools",
        "self-hosted",
        "rust programming",
        "kubernetes",
        "startup funding",
      ],
      limit: 20,
    },
    enabled: true,
  },
  {
    id: "github",
    source: "github",
    name: "GitHub Trending",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["New repos by stars"],
    options: { days: 7, limit: 25 },
    enabled: true,
  },
  {
    id: "huggingface",
    source: "huggingface",
    name: "Hugging Face Daily Papers",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["Daily papers"],
    options: { limit: 15 },
    enabled: true,
  },
  {
    id: "arxiv-cs-ai",
    source: "arxiv",
    name: "arXiv cs.AI",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["cs.AI"],
    options: { category: "cs.AI", limit: 20 },
    enabled: true,
  },
  {
    id: "arxiv-cs-cl",
    source: "arxiv",
    name: "arXiv cs.CL",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["cs.CL"],
    options: { category: "cs.CL", limit: 20 },
    enabled: true,
  },
  {
    id: "arxiv-cs-lg",
    source: "arxiv",
    name: "arXiv cs.LG",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["cs.LG"],
    options: { category: "cs.LG", limit: 20 },
    enabled: true,
  },
  {
    id: "lobsters",
    source: "lobsters",
    name: "Lobste.rs",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["Hottest"],
    options: { limit: 25 },
    enabled: true,
  },
  {
    id: "devto",
    source: "devto",
    name: "Dev.to",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["#ai"],
    options: { tag: "ai", limit: 15 },
    enabled: true,
  },
  {
    id: "producthunt",
    source: "producthunt",
    name: "Product Hunt",
    authType: "public_api",
    isConnected: true,
    monitoredChannels: ["Daily ranked"],
    options: { limit: 15 },
    enabled: false,
  },

  // News and blog feeds (RSS/Atom) - fetched directly in Rust, no browser.
  ...[
    { id: "techcrunch", name: "TechCrunch", feedUrl: "https://techcrunch.com/feed/" },
    { id: "theverge", name: "The Verge", feedUrl: "https://www.theverge.com/rss/index.xml" },
    { id: "arstechnica", name: "Ars Technica", feedUrl: "https://feeds.arstechnica.com/arstechnica/index" },
    { id: "infoq", name: "InfoQ", feedUrl: "https://feed.infoq.com/" },
    { id: "huggingface-blog", name: "Hugging Face Blog", feedUrl: "https://huggingface.co/blog/feed.xml" },
    { id: "deepmind", name: "Google DeepMind", feedUrl: "https://deepmind.google/blog/feed" },
    { id: "openai-news", name: "OpenAI News", feedUrl: "https://openai.com/news/rss.xml" },
    { id: "the-decoder", name: "The Decoder", feedUrl: "https://the-decoder.com/feed/" },
    { id: "syncedreview", name: "Synced", feedUrl: "https://syncedreview.com/feed/" },
    { id: "kdnuggets", name: "KDnuggets", feedUrl: "https://www.kdnuggets.com/feed" },
    {
      id: "towardsdatascience",
      name: "Towards Data Science",
      feedUrl: "https://towardsdatascience.com/feed/",
    },
    {
      id: "nvidia-dev-blog",
      name: "NVIDIA Developer Blog",
      feedUrl: "https://developer.nvidia.com/blog/feed",
    },
    { id: "github-blog", name: "GitHub Blog", feedUrl: "https://github.blog/feed/" },
    { id: "hn-frontpage", name: "Hacker News (RSS)", feedUrl: "https://news.ycombinator.com/rss" },
    { id: "stackoverflow-blog", name: "Stack Overflow Blog", feedUrl: "https://stackoverflow.blog/feed/" },
    { id: "thenewstack", name: "The New Stack", feedUrl: "https://thenewstack.io/feed" },
    { id: "smashingmagazine", name: "Smashing Magazine", feedUrl: "https://www.smashingmagazine.com/feed/" },
    { id: "css-tricks", name: "CSS-Tricks", feedUrl: "https://css-tricks.com/feed/" },
    { id: "freecodecamp", name: "freeCodeCamp", feedUrl: "https://www.freecodecamp.org/news/rss/" },
    { id: "sitepoint", name: "SitePoint", feedUrl: "https://www.sitepoint.com/sitepoint.rss" },
  ].map((feed): SourceConnection => ({
    id: feed.id,
    source: "rss",
    name: feed.name,
    authType: "public_api",
    isConnected: true,
    monitoredChannels: [new URL(feed.feedUrl).hostname.replace(/^www\./, "")],
    options: { feedUrl: feed.feedUrl, limit: 15 },
    enabled: true,
  })),
];
